// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-U2vny0THLh-LMcKoikH58fIYr2T_Uis',
    appId: '1:938720584355:web:c2dd697359e36013731516',
    messagingSenderId: '938720584355',
    projectId: 'hiking-app-56fa9',
    authDomain: 'hiking-app-56fa9.firebaseapp.com',
    databaseURL: 'https://hiking-app-56fa9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiking-app-56fa9.appspot.com',
    measurementId: 'G-VN6FCYRYWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwqF8Nwvrrcd6IKP3mMJMh0ej5cn4QRQ',
    appId: '1:938720584355:android:4207eeb38feaa6aa731516',
    messagingSenderId: '938720584355',
    projectId: 'hiking-app-56fa9',
    databaseURL: 'https://hiking-app-56fa9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiking-app-56fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeytMhOba5DnL7B3X38EQ9X--vbevT5eE',
    appId: '1:938720584355:ios:953c543dca55c0a4731516',
    messagingSenderId: '938720584355',
    projectId: 'hiking-app-56fa9',
    databaseURL: 'https://hiking-app-56fa9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiking-app-56fa9.appspot.com',
    iosBundleId: 'com.example.bachThes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeytMhOba5DnL7B3X38EQ9X--vbevT5eE',
    appId: '1:938720584355:ios:953c543dca55c0a4731516',
    messagingSenderId: '938720584355',
    projectId: 'hiking-app-56fa9',
    databaseURL: 'https://hiking-app-56fa9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiking-app-56fa9.appspot.com',
    iosBundleId: 'com.example.bachThes',
  );
}
