
@startuml
hide footbox

title Prijava
'funkcionalnost Prijava uporabnika

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

autonumber

actor "Uporabnik" as Uporabnik <<actor>>
participant "LoginPage" as LoginPage <<boundary>>
participant "LoginController" as LoginController<<control>>
participant "Firebase Authentication" as FbAuth <<database>>
participant "NavigationController" as Nav <<control>>
participant "MainPage" as MainPage <<boundary>>
participant "Shared Preferences" as prefs <<control>>
participant "Firebase Cloud Firestore" as db <<database>>


Uporabnik -> LoginPage: Izpolnitev prijave in klik na gumb prijava
activate LoginPage
LoginPage -> LoginController: signInUser(email, password)
deactivate LoginPage
activate LoginController
LoginController -> FbAuth: signUserInWithEmailAndPassword(email, password)
activate FbAuth
FbAuth --> LoginController: sporočilo o uspešni prijavi
deactivate FbAuth
LoginController -> Nav: NavigateToMainPage()
deactivate LoginController
activate Nav
Nav -> MainPage
deactivate Nav
activate MainPage
MainPage -> db: getHiker(currentUser.uid)
activate db
db -> MainPage: podatki o tem pohodniku
deactivate db
MainPage -> prefs: setCurrentHiker(id, username, email, points, ...)
activate prefs
prefs --> MainPage
deactivate prefs
MainPage -> Uporabnik: prikaz domačega zaslona


